### ISSUE TITLE
Multi-curative stop criterion

### ISSUE THREAD

**Issue by bqth29** [powsybl/powsybl-open-rao#1043]
### Describe the current behavior

Currently, the `curative-stop-criterion` parameter is common to all curative instants.

### Describe the expected behavior

For CSA SWE, in order to apply CRAs as soon as possible, it would be better to only use the `curative-stop-criterion` parameter for the last curative instant, and MAX_MIN_MARGIN for all the others.

**Comment by phiedw** [comment]
We will have to check with Alexandre ++ about this, it has the risk of leading to unoptimal results by using up too many actions at one instant and not having enough to secure the next instant. (in some processes the max ra per instant is "additive")
