### ISSUE TITLE
Improve performance of sensi computations with applied RAs

### ISSUE THREAD

**Issue by pet-mit** [powsybl/powsybl-open-rao#1061]
### Describe the current behavior

When computing sensitivity values with applied RAs, a network clone is created for every state with applied RAs.

### Describe the expected behavior

Improve performance by avoiding the creation of new clone, and instead re-using existing clones (but we will have to un-apply RAs in-between states). (see TODO in SystematicSensitivityAdapter around line 111)

### Describe the motivation

Performance boost

**Comment by Godelaine** [comment]
clone creation is now way faster than before, experiment was performed with limited success
