### ISSUE TITLE
Tests: clean-up angle monitoring steps

### ISSUE THREAD

**Issue by pet-mit** [powsybl/powsybl-open-rao#1062]
### Describe the current behavior

Angle monitoring steps in cucumber tests are not very clean: 
- Timestamps used for CRAc import and for GLSK import are not the same
- Load-flow parameters used are not fetched from RaoParameters
- ... ?

### Describe the expected behavior

Fix these issues and clean up the AngleMonitoringSteps as much as possible

**Comment by Godelaine** [comment]
done
