### ISSUE TITLE
Mutualize CRAC exporters

### ISSUE THREAD

**Issue by bqth29** [powsybl/powsybl-open-rao#1073]
### Describe the expected behavior

A similar work as carried out in #1069 must be done for CRAC exporters using `crac.write`.

**Comment by bqth29** [comment]
@pet-mit do you plan to include this in your PR or shall we do it in another one?

**Comment by pet-mit** [comment]
> @pet-mit do you plan to include this in your PR or shall we do it in another one?

we only have one crac exporter (json). there's nothing to do
