### ISSUE TITLE
Power Gradient Constraints

### ISSUE THREAD

**Issue by bqth29** [powsybl/powsybl-open-rao#1218]
### Describe the expected behavior

As introduced in #1208 (in [this comment](https://github.com/powsybl/powsybl-open-rao/issues/1208#issuecomment-2519958938)), the intertemporal RAO will require Power Gradient Constraints (PGCs).

Implement the `PowerGradientConstraint` class in `intertemporal-rao`.

### Extra Information

After some discussions, we concluded that there this no need, at first, to have a start and end validity dates for the constraints (though they may be required for other types of intertemporal constraints). Thus, the `PowerGradientConstraint` shall only have 3 attributes: the network element, the gradient value and the variation direction.

```java
public record PowerGradientConstraint(String networkElementId, double powerGradient, RangeAction.VariationDirection variationDirection) {
}
```

Besides, it could be worth to isolate the `VariationDirection` enum out of the `RangeAction` i,nterface in a standalone file in `crac-api`.

> Wait for #1186 to be merged before to address this issue.

**Comment by Godelaine** [comment]
Is the reason why you want to separate VariationDirection to reuse it for other constraints ?

**Comment by bqth29** [comment]
> Is the reason why you want to separate VariationDirection to reuse it for other constraints ?

No, it is because currently, the enum is part of the RangeAction interface. As it can also be used for gradient constraints I thought it would be cleaner to get it out as it will no longer be a specific RangeAction's field.
