### ISSUE TITLE
Add more precision on thresholds in CNE files.

### ISSUE THREAD

**Issue by phiedw** [powsybl/powsybl-open-rao#1244]
### Describe the current behavior

Currently in the SWE CNE, we round the thresholds to the closest integer. Because of this, in some CNEs, we end up with a flow value that seems lower than its limit, and so we end up with first_unsecure_cne files with no apparent overloads.

### Describe the expected behavior

We should add precision on the threshold just like we have added recently on the values. For instance if we have a flow of 456.73A and a threshold of 456.61A, we should export a threshold of 456.6A (instead of currently 457A). If we have a flow of 456.64A, we should this time export a threshold of 456.61A.

**Comment by Godelaine** [comment]
merged with 1245
