### ISSUE TITLE
OR-Tools Reference in Installation Guide not given

### ISSUE THREAD

**Issue by flexo90** [powsybl/powsybl-open-rao#33]
Regarding the Installation guide:

It would be helpful if a guide were included in the installation steps where to put the OR-Tools binaries from the google websites, and adding them to Farao so that the or-tools can be found by Farao during runtime. And to specify whether it is necessary to build or-tools from source or only install the binaries.

Kind regards,

**Comment by pet-mit** [comment]
Added to readme
