### ISSUE TITLE
Update GLSK handling for AngleMonitoring

### ISSUE THREAD

**Issue by pet-mit** [powsybl/powsybl-open-rao#890]
### Describe the current behavior

In the angle monitoring module, re-dispatching is applied by stopping generators identified in the remedial actions linked to the angle constraints, then re-dispatching the lost generation on the other generators in the GLSK.
In order to excluded the stopped generators from the GLSK before asking powsybl to re-dispatch the lost generation, specific code is written.

### Describe the expected behavior

Use powsybl's new ability to exclude generators from GLSK

### Describe the motivation

Cleaner code

**Comment by Godelaine** [comment]
merged : https://github.com/powsybl/powsybl-open-rao/pull/1092
