### ISSUE TITLE
Use TwoSides and ThreeSides

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-open-rao#908]
### Describe the current behavior

Before using the `powsybl-core` remedial actions in powsybl-open-rao, we have to think of a small refactoring to remove Side.LEFT and Side.RIGHT to TwoSides enum (an maybe ThreeSides).  

### Describe the expected behavior

- The question of CRAC JSON breaking change in its format must be decided. 
- If yes, the question of backward compatibility has to be decided. 
- Documentation must be adapted (all website examples).

**Comment by pjeanmarie** [comment]
Do we update Crac json ("side" : "left")?
also parameter json ("default-monitored-line-side" : "monitor-lines-on-left-side")?
also RaoResults json ("leftSide" : {...)?

**Comment by pjeanmarie** [comment]
com.powsybl.openrao.data.cracapi.cnec.Side no longer exist, is it a breaking change?

**Comment by phiedw** [comment]
I would say yes replace also in the json files, while keeping retro compatibility.
And it probably is indeed a breaking change for some parts of gridcapa.

**Comment by pjeanmarie** [comment]
Updated json crac 2.4 and new version 1.5 for json raoResult.
But for the json crac creation parameters with "default-monitored-line-side" with values "monitor-lines-on-left/right/both-side", it seems this file do not have version system, can I keep it like that or do I have to add a version system fo this files two?
