### ISSUE TITLE
Only apply RAs that currently have an impact on the network

### ISSUE THREAD

**Issue by murgeyseb** [powsybl/powsybl-open-rao#921]
### Describe the current behavior

Currently, especially for automatic remedial action, OpenRAO can report some remedial actions as applied even if they do not have any impact on the underlying network (e.g. RAs already applied in previous states, or on the initial network).

### Describe the expected behavior

OpenRAO should not report remedial actions as applied on a given state if they do not have any impact on the network for this state.

### Describe the motivation

The aim is to avoid reporting remedial actions that are not actually needed nor applied.

**Comment by pet-mit** [comment]
Fixed in https://github.com/powsybl/powsybl-open-rao/pull/922
